### ISSUE TITLE
"Check step status" goes down with null pointer exception

### ISSUE THREAD

**Issue by teners** [StepicOrg/intellij-plugin#2]
It seems that the problem is [here](https://github.com/StepicOrg/intellij-plugin/blob/master/src/main/actions/popupMenu/GetStepStatus.java#L59) (line 59). 
I just downloaded the plugin and started to watch the course on Stepic, so I didn't submit any solutions, just made a new Stepic project in IDEA and tried to check step status.

**Comment by 2Pit** [comment]
Добрый день!

К сожалению, у меня никак не получается воспроизвести вашу ошибку.
Не могли бы вы уточнить:
1. версию intellij IDEA,
2. повторяется ли ошибка,
3. прошла ли авторизация 
если Main menu > Stepic > Who am i    вернет Anonymous ..num.., то нет.

Что же касается самой ошибки, то там действительно может возникать NPE. Однако из известных мне случаев только из-за проблем с интернет соединением. Даже при неправильных запросах должен быть пустой лист.

**Comment by teners** [comment]
IntelliJ IDEA 2016.1.3, build IU-145.1617
Вчера проверял несколько раз, ошибка повторялась. Соединение было, потому что Who I am возвращал корректный результат. 
Сейчас ещё раз проверил, Who I am так же работает, но при попытке получить step status получаю вот такое исключение: 
`java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)`
Полный backtrace [здесь](http://pastebin.com/SwKwQbeM).
После перезапуска IDEA сначала снова получил JsonSyntaxException, попробовал ещё раз – опять NullPointerException

**Comment by 2Pit** [comment]
Никак не могу отловить эту ошибку, хотя в IntelliJ IDEA 2016.1.5 плагин в целом работает не стабильно. Есть NPE возникающие только один раз. 
Возможно ошибка была в библиотеке GSON, она используется для десериализации json-ов. Я её в плагин не импортировал и загружалась библиотека пользователя. 

Сейчас она добавлена но пока в unstable версии:
https://drive.google.com/open?id=0B3r_Au4BpPbwWklYYU9WS2EwUTA

Было бы круто, если бы ты её протестировал.

**Comment by teners** [comment]
Поставил unstable версию, всё тот же NPE. 

Ещё, кстати, когда обновил плагин, Idea попросила перелогиниться (в проекте что-то сломалось, и я так понимаю, так и должно быть), неправильно ввёл пароль и поймал RuntimeException. Так и не нашёл где можно перелогиниться, Who am I возвращала "Anonymous xxx". Затем несколько раз пересоздавал проект с неправильным паролем (снова пыался поймать RuntimeException, вообще никаких ошибок, но whoami всё ещё возвращал "Anonymous"). 

Надо будет попробовать что-нибудь засабмиттить и снова попробовать проверить step status, я думаю.

**Comment by 2Pit** [comment]
Да, забыл предупредить, что авторизация сломается. 
Update course - будет пытаться это починить, но это еще не работает.
Кроме того плагин совместим не только со 150ым курсом, но и с курсом Куликова по алгоритмам. Мы этого не анонсировали из-за ограниченного доступа.

**Comment by 2Pit** [comment]
Закрываю. Сейчас внезапные ошибки не вылетают.
Спасибо за содействие!
